# Generated by Django 2.1.7 on 2020-05-30 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'OBS Scene'), (2, 'Media file'), (3, 'Live media')])),
                ('scene_name', models.CharField(blank=True, max_length=100)),
                ('media_path', models.CharField(blank=True, max_length=100)),
                ('target', models.DateTimeField(null=True)),
                ('duration', models.DurationField(default=60)),
                ('lock_duration', models.BooleanField(default=False)),
                ('transition_effect', models.CharField(blank=True, max_length=100)),
                ('wait_signal', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['target'],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='sequence',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='timeline.Show'),
        ),
        migrations.AddField(
            model_name='live',
            name='active_sequence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeline.Sequence'),
        ),
        migrations.AddField(
            model_name='live',
            name='active_show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='timeline.Show'),
        ),
        migrations.AlterUniqueTogether(
            name='sequence',
            unique_together={('name', 'show')},
        ),
    ]
